FROM golang:latest as builder
WORKDIR /events

ARG GOPROXY
ENV GOPROXY=${GOPROXY:-https://proxy.golang.org,direct}

COPY go.mod go.mod
COPY go.sum go.sum

#RUN go mod download
#
#COPY ./cmd cmd/
#COPY ./pkg pkg/
RUN CGO_ENABLED=0 GO111MODULE=on go build -a -o ./bin/events-exporter ./cmd/main.go

FROM gcr.io/distroless/base
WORKDIR /
COPY --from=builder /events/bin/events-exporter /usr/local/bin/events-exporter
USER nonroot:nonroot

ENTRYPOINT ["events-exporter"]